namespace Fornach.Domain

/// Snapshot context passed to triggers when an action resolves
type TriggerContext =
  { ActorId: CombatantId
    TargetId: CombatantId
    DamageDealt: int
    Plane: Plane
    IsCritical: bool
    IsGambit: bool }

/// Discrete mechanical side-effects generated by equipment procs
type TriggerEffect =
  /// Applies debuff delta to a specific meter on either the self or opponent
  | InflictDebuff of targetIsSelf: bool * meterName: string * amount: int
  /// Deals flat bonus damage bypassing normal roll calculations
  | BonusDamage of plane: Plane * amount: int
  /// Restores a flat amount to Health (true) or Morale (false)
  | RestorePool of poolIsHealth: bool * amount: int
  /// Grants study / insight stacks to the owner
  | GainStudyStacks of amount: int
  /// Triggers an immediate reactive retaliation strike
  | FreeCounterStrike of plane: Plane * flatDamage: int
  /// Degrades target physical armor durability
  | ShredTargetArmor of amount: int

/// Interception phases where equipment hooks can execute
type EquipmentTrigger =
  /// Fires before damage is dealt when an attack is declared
  | OnAttackDeclared of (TriggerContext -> TriggerEffect list)
  /// Fires when an attack successfully lands and deals damage > 0
  | OnHitLanded of (TriggerContext -> TriggerEffect list)
  /// Fires specifically when a disparity threshold or critical strike occurs
  | OnCriticalStrike of (TriggerContext -> TriggerEffect list)
  /// Defensive hook: fires when the wearer receives damage
  | OnDamageReceived of (TriggerContext -> TriggerEffect list)
